version: '3.4'

services:
  nodemysqlfetchnews2024:
    image: nodemysqlfetchnews2024
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
